"use client";

import { AssistantRuntimeProvider } from "@assistant-ui/react";
import { useChatRuntime, AssistantChatTransport } from "@assistant-ui/react-ai-sdk";
import { routerAbDataSchemas } from "@/lib/assistant-ui/router-ab-data-schemas";
import { lastAssistantMessageIsCompleteWithToolCalls, type UIMessage } from "ai";
import { Sidebar } from "@/components/assistant-ui/sidebar";
import { Thread } from "@/components/assistant-ui/thread";
import { RouterAbToggle, ReasoningLevelSelect } from "@/components/assistant-ui/router-ab-controls";
import { KbdHint } from "@/components/kbd-hint";
import { Button } from "@/components/ui/button";
import { useMediaQuery } from "@/components/layout/use-media-query";
import { ChevronDown, Menu } from "lucide-react";
import { Dialog as DialogPrimitive } from "radix-ui";
import { useCallback, useEffect, useMemo, useRef, useState, type FC } from "react";

import {
  SHORTCUT_TARGETS,
  type ShortcutTarget,
  eventMatchesCombo,
  isTypingTarget,
} from "@/lib/shortcuts";
import { messageRowsToUIMessages } from "@/lib/assistant-ui/thread-messages";

/**
 * Click or focus the element that owns a given shortcut target.
 *
 * - For New chat / User settings / Select model: the element is a button,
 *   so we call .click() which fires its onClick handler.
 * - For Search chats: the element is the <input>, so we focus it.
 * - For Help: the element is a button, .click() opens the dialog.
 * - For Focus composer: the element is the composer <textarea>, so we
 *   focus it.
 */
function triggerTarget(target: ShortcutTarget) {
  if (typeof document === "undefined") return;
  const el = document.querySelector<HTMLElement>(`[data-shortcut-target="${target}"]`);
  if (!el) return;
  if (target === SHORTCUT_TARGETS.searchChats || target === SHORTCUT_TARGETS.focusComposer) {
    el.focus();
    if (el instanceof HTMLInputElement) el.select();
  } else {
    el.click();
  }
}

type ReasoningLevel = "low" | "medium" | "high";
type ModelTier = "cheap" | "expensive";

type ModelOption = {
  providerId: string;
  providerLabel: string;
  modelId: string;
  modelLabel: string;
  enabled: boolean;
  reason?: string;
  accessPath?: "openai_api" | "minimax_api" | "codex_chatgpt";
  billingLabel?: "API billed" | "MiniMax token plan" | "ChatGPT subscription";
  capabilityKind?: "model_provider" | "agent_backend";
  description?: string;
  reasoningLevels: ReadonlyArray<ReasoningLevel>;
  tier: ModelTier;
};

function selectedAccessExplanation(model: ModelOption | undefined): string {
  if (!model) return "";
  if (model.accessPath === "minimax_api") {
    return "Access: MiniMax API key · MiniMax token plan/subscription";
  }
  if (model.accessPath === "codex_chatgpt") {
    return "Access: Codex CLI · ChatGPT subscription";
  }
  return "Access: OpenAI API key · API billed";
}

type ModelsResponse = {
  models: ModelOption[];
  defaultModelId: string | null;
  defaultReasoningLevel: ReasoningLevel;
};

type ThreadListItem = {
  id: string;
  title: string;
  createdAt?: string;
  updatedAt?: string;
};

type MessageRow = {
  id: string;
  threadId: string;
  role: "user" | "assistant" | "system";
  content: string | null;
  parts: unknown;
  modelId: string | null;
  createdAt: string;
  rating?: "up" | "down" | null;
};

type ThreadsResponse = {
  threads: ThreadListItem[];
  configured: boolean;
};

type MessagesResponse = {
  thread: ThreadListItem | null;
  messages: MessageRow[];
  configured: boolean;
};

// Stub sidebar entries shown before the persisted thread list loads. The
// "local-" prefix keeps them on the offline-only code path (see isLocalThreadId
// below and the same-prefix guards in components/assistant-ui/thread.tsx) so
// they can never reach the persisted-chat API.
const INITIAL_THREADS: ThreadListItem[] = [
  { id: "local-1", title: "Control Room setup" },
  { id: "local-2", title: "Learn Chinese workflow" },
  { id: "local-3", title: "Hermes server task" },
  { id: "local-4", title: "Finance article draft" },
];

// Thread ids that exist only in this browser session and must never hit the
// persisted-chat API. Used for the offline stub entries above and for the
// in-memory "New chat" entries generated by handleNewThread, all of which are
// prefixed with "local-".
function isLocalThreadId(id: string | null | undefined): boolean {
  return !id || id.startsWith("local-");
}

const ChatPane: FC<{
  modelId: string | null;
  threadId: string | null;
  initialMessages: UIMessage[];
  notesDisabled: boolean;
  routerAbOn: boolean;
  reasoningLevel: ReasoningLevel;
  models: ModelOption[];
  onFinish: () => void;
}> = ({
  modelId,
  threadId,
  initialMessages,
  notesDisabled,
  routerAbOn,
  reasoningLevel,
  models,
  onFinish,
}) => {
  const selectedModel = models.find((m) => m.modelId === modelId) ?? null;
  const effectiveRouterAbOn = routerAbOn && selectedModel?.providerId === "openai";
  const transport = useMemo(
    () =>
      new AssistantChatTransport({
        api: "/api/chat",
        // Static body bits only. We use `prepareSendMessagesRequest` to inject
        // the *current* reasoning level + routerAb toggle at send time so
        // changes between sends are reflected in the next request.
        body: { modelId, threadId },
        prepareSendMessagesRequest: ({ body, messages }) => ({
          body: {
            ...body,
            messages,
            modelId,
            threadId,
            reasoningLevel,
            routerAb: effectiveRouterAbOn,
          },
        }),
      }),
    [modelId, threadId, reasoningLevel, effectiveRouterAbOn],
  );

  const runtime = useChatRuntime({
    id: threadId ?? undefined,
    messages: initialMessages,
    onFinish,
    sendAutomaticallyWhen: lastAssistantMessageIsCompleteWithToolCalls,
    transport,
    // Type-validate the Router A/B data parts emitted by /api/chat and
    // keep them attached to the assistant message state so the panel can
    // pick them up via `useAuiState((s) => s.message.parts)`.
    dataPartSchemas: routerAbDataSchemas,
  });

  return (
    <AssistantRuntimeProvider runtime={runtime}>
      <Thread threadId={threadId} notesDisabled={notesDisabled} routerAbOn={effectiveRouterAbOn} />
    </AssistantRuntimeProvider>
  );
};

const ModelSelector: FC<{
  models: ModelOption[];
  selectedModelId: string | null;
  onModelChange: (modelId: string) => void;
  loading: boolean;
}> = ({ models, selectedModelId, onModelChange, loading }) => {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const isPhone = useMediaQuery("(max-width: 639px)");

  useEffect(() => {
    if (isPhone) return;
    const handleClickOutside = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [isPhone]);

  const selected = models.find((m) => m.modelId === selectedModelId);
  const triggerLabel = selected
    ? selected.modelLabel
    : loading
      ? "Loading models…"
      : "Select model";
  const selectedExplanation = selectedAccessExplanation(selected);

  const modelOptions = (() => {
    // Assign ⌘1..⌘9 to the first 9 *enabled* models in display order.
    // This way the "press ⌘3 to switch to the third enabled model"
    // behavior is consistent with what the user sees in the list.
    const enabledIndexById = new Map<string, number>();
    let enabledCounter = 0;
    for (const m of models) {
      if (!m.enabled) continue;
      enabledCounter += 1;
      if (enabledCounter <= 9) {
        enabledIndexById.set(m.modelId, enabledCounter);
      }
    }
    return models.map((m) => {
      const isSelected = m.modelId === selectedModelId;
      const disabled = !m.enabled;
      const shortcutIndex = enabledIndexById.get(m.modelId);
      return (
        <button
          key={`${m.providerId}:${m.modelId}`}
          type="button"
          disabled={disabled}
          title={disabled ? (m.reason ?? "Not available") : undefined}
          onClick={() => {
            if (disabled) return;
            onModelChange(m.modelId);
            setOpen(false);
          }}
          className={
            "flex min-h-10 w-full items-center gap-2 px-3 py-2 text-left text-xs transition-colors sm:min-h-0 sm:py-1.5 " +
            (disabled
              ? "cursor-not-allowed text-muted-foreground/60"
              : isSelected
                ? "bg-accent text-accent-foreground"
                : "text-popover-foreground hover:bg-accent/50 hover:text-accent-foreground")
          }
        >
          <div className="min-w-0 flex-1">
            <div className="truncate font-medium">{m.modelLabel}</div>
            <div className="flex flex-wrap items-center gap-1 truncate text-[10px] text-muted-foreground">
              <span>{m.billingLabel ?? m.providerLabel}</span>
              {m.accessPath === "minimax_api" ? <span>· MiniMax key</span> : null}
              {m.accessPath === "openai_api" ? <span>· OpenAI key</span> : null}
              {disabled && m.reason ? <span>— {m.reason}</span> : null}
            </div>
          </div>
          {shortcutIndex !== undefined && (
            <KbdHint
              combo={`${shortcutIndex}`}
              className="aui-model-dropdown-shortcut bg-background/40"
            />
          )}
        </button>
      );
    });
  })();

  return (
    <div
      ref={ref}
      className="relative flex items-center border-b border-border/60 bg-background px-3 py-2 sm:px-4"
    >
      <button
        type="button"
        onClick={() => setOpen((prev) => !prev)}
        data-shortcut-target={SHORTCUT_TARGETS.selectModel}
        aria-label={`Select model (currently ${triggerLabel}; press M)`}
        className="aui-model-selector-trigger relative inline-flex min-h-10 max-w-full items-center gap-1.5 rounded-md border border-border/50 bg-muted/20 py-1 pl-2.5 pr-8 text-xs font-medium text-muted-foreground transition-colors hover:border-border hover:bg-muted/40 hover:text-foreground sm:min-h-0 sm:pr-10"
        disabled={loading}
      >
        <span className="size-1.5 rounded-full bg-emerald-500/80" aria-hidden />
        <span className="truncate">{triggerLabel}</span>
        {selected?.billingLabel ? (
          <span className="hidden shrink-0 rounded bg-background/70 px-1.5 py-0.5 text-[10px] text-muted-foreground sm:inline">
            {selected.billingLabel}
          </span>
        ) : null}
        <ChevronDown className="size-3 shrink-0 opacity-70" />
        <KbdHint
          combo="m"
          className="aui-model-selector-shortcut pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 bg-background/60"
        />
      </button>

      {selectedExplanation ? (
        <div className="ml-2 hidden min-w-0 truncate text-[11px] text-muted-foreground md:block">
          {selectedExplanation}
        </div>
      ) : null}

      {open && !isPhone && (
        <div className="absolute left-4 top-full z-50 mt-1 max-h-80 w-64 overflow-y-auto rounded-md border border-border bg-popover py-1 shadow-md">
          {models.length === 0 && !loading && (
            <div className="px-3 py-2 text-xs text-muted-foreground">No models available</div>
          )}
          {modelOptions}
        </div>
      )}

      <DialogPrimitive.Root open={open && isPhone} onOpenChange={setOpen}>
        <DialogPrimitive.Portal>
          <DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/40 data-[state=closed]:animate-out data-[state=open]:animate-in data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0" />
          <DialogPrimitive.Content className="fixed inset-x-0 bottom-0 z-50 max-h-[70dvh] overflow-hidden rounded-t-2xl border border-border bg-popover shadow-lg outline-none data-[state=closed]:animate-out data-[state=open]:animate-in data-[state=closed]:slide-out-to-bottom data-[state=open]:slide-in-from-bottom">
            <div className="safe-bottom flex max-h-[70dvh] flex-col">
              <div className="border-b border-border/60 px-4 py-3">
                <DialogPrimitive.Title className="text-sm font-semibold text-popover-foreground">
                  Select model
                </DialogPrimitive.Title>
                <DialogPrimitive.Description className="mt-1 text-xs text-muted-foreground">
                  Choose the model/backend for this chat. Access path and billing are shown for each
                  option.
                </DialogPrimitive.Description>
              </div>
              <div className="overflow-y-auto py-1">
                {models.length === 0 && !loading && (
                  <div className="px-4 py-3 text-xs text-muted-foreground">No models available</div>
                )}
                {modelOptions}
              </div>
            </div>
          </DialogPrimitive.Content>
        </DialogPrimitive.Portal>
      </DialogPrimitive.Root>
    </div>
  );
};

/**
 * Row of secondary controls that live below the model picker:
 *   - the reasoning-level dropdown (Side A's reasoning effort),
 *   - the Router A/B on/off toggle.
 *
 * The reasoning-level dropdown is always visible — Side A always uses the
 * user's pick — and only lists levels supported by the currently-selected
 * model. The A/B toggle controls whether the recommender runs at all.
 */
const RouterControlsBar: FC<{
  models: ModelOption[];
  selectedModelId: string | null;
  reasoningLevel: ReasoningLevel;
  onReasoningChange: (next: ReasoningLevel) => void;
  routerAbOn: boolean;
  onRouterAbChange: (next: boolean) => void;
}> = ({
  models,
  selectedModelId,
  reasoningLevel,
  onReasoningChange,
  routerAbOn,
  onRouterAbChange,
}) => {
  const selectedModel = useMemo(
    () => models.find((m) => m.modelId === selectedModelId) ?? null,
    [models, selectedModelId],
  );
  const supportedLevels: ReadonlyArray<ReasoningLevel> = selectedModel
    ? selectedModel.reasoningLevels
    : ["low"];
  const supportsReasoningControls = supportedLevels.length > 0;
  const supportsRouterAb = selectedModel?.providerId === "openai";
  // If the persisted reasoning level is no longer supported by the new
  // model, snap to the cheapest supported level so the dropdown stays sane.
  useEffect(() => {
    if (supportedLevels.includes(reasoningLevel)) return;
    if (supportedLevels.length === 0) return;
    onReasoningChange(supportedLevels[0]);
  }, [supportedLevels, reasoningLevel, onReasoningChange]);
  useEffect(() => {
    if (supportsRouterAb || !routerAbOn) return;
    onRouterAbChange(false);
  }, [supportsRouterAb, routerAbOn, onRouterAbChange]);
  return (
    <div className="flex flex-wrap items-center gap-2 border-b border-border/60 bg-background px-3 py-2 sm:px-4">
      {supportsReasoningControls ? (
        <ReasoningLevelSelect
          value={reasoningLevel}
          options={supportedLevels}
          onChange={onReasoningChange}
        />
      ) : (
        <div className="rounded-md border border-border/50 bg-muted/20 px-2 py-1 text-xs text-muted-foreground">
          Reasoning controls are not supported for this provider.
        </div>
      )}
      {supportsRouterAb ? (
        <RouterAbToggle on={routerAbOn} onToggle={onRouterAbChange} />
      ) : (
        <div className="rounded-md border border-border/50 bg-muted/20 px-2 py-1 text-xs text-muted-foreground">
          Router A/B is OpenAI-only.
        </div>
      )}
    </div>
  );
};

const MobileHeader: FC<{
  activeThreadTitle: string;
  onOpenSidebar: () => void;
}> = ({ activeThreadTitle, onOpenSidebar }) => {
  return (
    <header className="safe-top flex min-h-14 items-center gap-2 border-b border-border/60 bg-background px-3 md:hidden">
      <Button
        type="button"
        variant="ghost"
        size="icon-lg"
        aria-label="Open sidebar"
        onClick={onOpenSidebar}
        className="-ml-1 rounded-full"
      >
        <Menu className="size-5" />
      </Button>
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm font-semibold text-foreground">Control Room</div>
        <div className="truncate text-[11px] text-muted-foreground/70">{activeThreadTitle}</div>
      </div>
    </header>
  );
};

const SidebarPanel: FC<{
  threads: { id: string; title: string }[];
  activeThreadId: string;
  onSelectThread: (id: string) => void;
  onNewThread: () => void;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}> = ({ threads, activeThreadId, onSelectThread, onNewThread, open, onOpenChange }) => {
  return (
    <>
      <div className="hidden h-full shrink-0 md:block">
        <Sidebar
          threads={threads}
          activeThreadId={activeThreadId}
          onSelectThread={onSelectThread}
          onNewThread={onNewThread}
        />
      </div>

      <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}>
        <DialogPrimitive.Portal>
          <DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/40 md:hidden data-[state=closed]:animate-out data-[state=open]:animate-in data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0" />
          <DialogPrimitive.Content className="safe-top fixed inset-y-0 left-0 z-50 h-dvh w-72 max-w-[85vw] border-r border-border/60 bg-background outline-none md:hidden data-[state=closed]:animate-out data-[state=open]:animate-in data-[state=closed]:slide-out-to-left data-[state=open]:slide-in-from-left">
            <DialogPrimitive.Title className="sr-only">Control Room sidebar</DialogPrimitive.Title>
            <DialogPrimitive.Description className="sr-only">
              Search chats, start a new chat, or switch threads.
            </DialogPrimitive.Description>
            <Sidebar
              threads={threads}
              activeThreadId={activeThreadId}
              onSelectThread={onSelectThread}
              onNewThread={onNewThread}
              onClose={() => onOpenChange(false)}
            />
          </DialogPrimitive.Content>
        </DialogPrimitive.Portal>
      </DialogPrimitive.Root>
    </>
  );
};

export const Assistant = () => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  const [threads, setThreads] = useState<ThreadListItem[]>(INITIAL_THREADS);
  const [activeThreadId, setActiveThreadId] = useState<string | null>(
    INITIAL_THREADS[0]?.id ?? null,
  );
  const [threadMessages, setThreadMessages] = useState<UIMessage[]>([]);
  const [threadsLoading, setThreadsLoading] = useState(true);
  const [messagesLoading, setMessagesLoading] = useState(false);
  const [dbConfigured, setDbConfigured] = useState(true);
  const [models, setModels] = useState<ModelOption[]>([]);
  const [modelsLoading, setModelsLoading] = useState(true);
  const [modelsError, setModelsError] = useState<string | null>(null);
  const [selectedModelId, setSelectedModelId] = useState<string | null>(null);
  const [selectedReasoningLevel, setSelectedReasoningLevel] = useState<ReasoningLevel>("low");
  const [routerAbOn, setRouterAbOn] = useState(true);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const isCoarsePointer = useMediaQuery("(pointer: coarse)");
  const newChatCounter = useRef(0);

  const refreshThreads = useCallback(async () => {
    try {
      const res = await fetch("/api/threads", { cache: "no-store" });
      if (!res.ok) throw new Error(`status ${res.status}`);
      const data: ThreadsResponse = await res.json();
      setDbConfigured(data.configured);
      if (data.configured) {
        setThreads(data.threads);
        setActiveThreadId((prev) =>
          prev && data.threads.some((t) => t.id === prev) ? prev : (data.threads[0]?.id ?? null),
        );
      }
    } catch {
      setDbConfigured(false);
      setThreads((prev) => (prev.length ? prev : INITIAL_THREADS));
      setActiveThreadId((prev) => prev ?? INITIAL_THREADS[0]?.id ?? null);
    } finally {
      setThreadsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!mounted) return;
    void refreshThreads();
  }, [mounted, refreshThreads]);

  useEffect(() => {
    if (!mounted) return;
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/models", { cache: "no-store" });
        if (!res.ok) throw new Error(`status ${res.status}`);
        const data: ModelsResponse = await res.json();
        if (cancelled) return;
        setModels(data.models);
        setSelectedModelId((prev) =>
          prev && data.models.some((m) => m.modelId === prev && m.enabled)
            ? prev
            : data.defaultModelId,
        );
        setSelectedReasoningLevel((prev) =>
          prev && data.defaultReasoningLevel ? prev : data.defaultReasoningLevel,
        );
        setModelsError(null);
      } catch (err) {
        if (cancelled) return;
        setModelsError(err instanceof Error ? err.message : "Failed to load models");
      } finally {
        if (!cancelled) setModelsLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [mounted]);

  useEffect(() => {
    if (!mounted || isLocalThreadId(activeThreadId)) {
      setThreadMessages([]);
      return;
    }
    let cancelled = false;
    setMessagesLoading(true);
    (async () => {
      try {
        const res = await fetch(`/api/threads/${activeThreadId}/messages`, { cache: "no-store" });
        if (!res.ok) throw new Error(`status ${res.status}`);
        const data: MessagesResponse = await res.json();
        if (cancelled) return;
        setDbConfigured(data.configured);
        setThreadMessages(messageRowsToUIMessages(data.messages));
        if (data.thread) {
          setThreads((prev) =>
            prev.map((t) => (t.id === data.thread?.id ? { ...t, ...data.thread } : t)),
          );
        }
      } catch {
        if (!cancelled) setThreadMessages([]);
      } finally {
        if (!cancelled) setMessagesLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [mounted, activeThreadId]);

  const handleNewThread = useCallback(async () => {
    if (dbConfigured) {
      try {
        const res = await fetch("/api/threads", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ title: "New chat", modelId: selectedModelId }),
        });
        if (!res.ok) throw new Error(`status ${res.status}`);
        const data: { thread: ThreadListItem } = await res.json();
        setThreads((prev) => [data.thread, ...prev.filter((t) => t.id !== data.thread.id)]);
        setActiveThreadId(data.thread.id);
        setThreadMessages([]);
        return;
      } catch {
        setDbConfigured(false);
      }
    }

    newChatCounter.current += 1;
    const newThread = {
      id: `local-${Date.now()}-${newChatCounter.current}`,
      title: `New chat ${newChatCounter.current}`,
    };
    setThreads((prev) => [newThread, ...prev]);
    setActiveThreadId(newThread.id);
    setThreadMessages([]);
  }, [dbConfigured, selectedModelId]);

  const handleSelectThread = useCallback((id: string) => {
    setActiveThreadId(id);
    setSidebarOpen(false);
  }, []);

  // Centralized keyboard-shortcut handler. See lib/shortcuts.ts for the
  // full registry. The typing guard (isTypingTarget) is enforced here for
  // every shortcut marked requiresIdle in SHORTCUT_ENTRIES, so we never
  // hijack a key the user is typing into an input / textarea /
  // contenteditable. We also bail on e.repeat and on modifier keys for
  // single-key shortcuts, so the user can still use browser shortcuts
  // like Cmd+N (Firefox new window) or Cmd+Shift+; without our handler
  // firing first.
  useEffect(() => {
    if (!mounted) return;
    const handler = (e: KeyboardEvent) => {
      if (e.repeat) return;
      if (eventMatchesCombo(e, "mod+/")) {
        e.preventDefault();
        const help = document.querySelector<HTMLElement>(
          `[data-shortcut-target="${SHORTCUT_TARGETS.help}"]`,
        );
        help?.click();
        return;
      }
      const idle = !isTypingTarget(e.target);
      if (isCoarsePointer) return;
      if (idle) {
        const noMods = !e.metaKey && !e.ctrlKey && !e.altKey;
        if (noMods) {
          const k = e.key.toLowerCase();
          if (k >= "1" && k <= "9") {
            const idx = Number(k) - 1;
            const enabled = models.filter((m) => m.enabled);
            const target = enabled[idx];
            if (target) {
              e.preventDefault();
              setSelectedModelId(target.modelId);
              return;
            }
          }
          let target: ShortcutTarget | null = null;
          if (k === "n") target = SHORTCUT_TARGETS.newChat;
          else if (k === "k") target = SHORTCUT_TARGETS.searchChats;
          else if (k === "m") target = SHORTCUT_TARGETS.selectModel;
          else if (k === "c") target = SHORTCUT_TARGETS.focusComposer;
          else if (k === ",") target = SHORTCUT_TARGETS.userSettings;
          if (target) {
            e.preventDefault();
            triggerTarget(target);
          }
        }
      }
    };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [mounted, models, isCoarsePointer]);

  if (!mounted) return <div className="h-dvh" />;

  const activeThreadTitle =
    threads.find((thread) => thread.id === activeThreadId)?.title ?? "New chat";

  return (
    <div className="flex h-dvh overflow-hidden">
      <SidebarPanel
        threads={threads}
        activeThreadId={activeThreadId ?? ""}
        onSelectThread={handleSelectThread}
        onNewThread={handleNewThread}
        open={sidebarOpen}
        onOpenChange={setSidebarOpen}
      />

      <div className="flex h-full min-w-0 flex-1 flex-col overflow-hidden">
        <MobileHeader
          activeThreadTitle={activeThreadTitle}
          onOpenSidebar={() => setSidebarOpen(true)}
        />

        <ModelSelector
          models={models}
          selectedModelId={selectedModelId}
          onModelChange={setSelectedModelId}
          loading={modelsLoading}
        />

        <RouterControlsBar
          models={models}
          selectedModelId={selectedModelId}
          reasoningLevel={selectedReasoningLevel}
          onReasoningChange={setSelectedReasoningLevel}
          routerAbOn={routerAbOn}
          onRouterAbChange={setRouterAbOn}
        />

        {!dbConfigured && (
          <div className="border-b border-border bg-amber-500/10 px-4 py-2 text-xs text-amber-700 dark:text-amber-300">
            Working offline — chats and notes in this session may not persist.
          </div>
        )}

        {modelsError && (
          <div className="border-b border-border bg-destructive/10 px-4 py-2 text-xs text-destructive">
            Failed to load models: {modelsError}
          </div>
        )}

        <div className="min-h-0 flex-1 overflow-hidden">
          {messagesLoading ? (
            <div className="flex h-full items-center justify-center text-sm text-muted-foreground">
              Loading thread…
            </div>
          ) : (
            <ChatPane
              key={activeThreadId ?? "empty"}
              modelId={selectedModelId}
              threadId={activeThreadId}
              initialMessages={threadMessages}
              notesDisabled={!dbConfigured || threadsLoading}
              routerAbOn={routerAbOn}
              reasoningLevel={selectedReasoningLevel}
              models={models}
              onFinish={() => void refreshThreads()}
            />
          )}
        </div>
      </div>
    </div>
  );
};
